name: test
description: test
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: false
    - uses: Profpatsch/action-post-run@master
      with:
        run: |
          echo post-run
          echo post-run multiline
          date
          for i in 1 2 3; do
              echo "i is ${i}"
          done
