name: test
description: test
runs:
  using: 'composite'
  steps:
    - uses: Profpatsch/action-post-run@master
      with:
        run: |
          echo post-run
          echo post-run multiline
